name: "Build & Test"
on: push
jobs:

  ktlint:
    name: Run ktlint check
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.41.0/ktlint && chmod a+x ktlint
      - name: Run ktlint (Android)
        run: |
          ./ktlint -F "**/src/**/*.kt" "!**/generated/**" --android --reporter=plain?group_by_file

  unit_tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Create google-services.json file"
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json
      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: gradle/gradle-build-action@v2.1.0
        with:
          arguments: :app:test --stacktrace

  build_app:
    name: "Build app"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Create google-services.json file"
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json
      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: gradle/gradle-build-action@v2.1.0
        with:
          arguments: assembleDebug --stacktrace