name: "Build & Test"
on: push
jobs:
  create_google_services_json:
    name: "Create google-services.json"
    runs-on: ubuntu-latest
    env:
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
    steps:
      - name: Setup Node v18
        uses: actions/setup-node@v2
        with:
          node-version: 18
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json

  unit_tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: gradle/gradle-build-action@v2.1.0
        with:
          arguments: :app:test --stacktrace

  build_app:
    name: "Build app"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: gradle/gradle-build-action@v2.1.0
        with:
          arguments: assembleDebug --stacktrace