name: "Build & Test"
on: push
jobs:
  sample-step:
    runs-on: ubuntu-latest
    steps:
      - name: "Greet"
        run: echo "Hello world!"

  unit_tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: gradle/gradle-build-action@v2.1.0
        with:
          arguments: :app:test --stacktrace

  build_app:
    name: "Build app"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: gradle/gradle-build-action@v2.1.0
        with:
          arguments: assembleDebug --stacktrace